// frontend/src/views/auth/Login.vue
<template>
  <div class="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
    <div class="max-w-md w-full space-y-8">
      <div>
        <h2 class="mt-6 text-center text-3xl font-extrabold text-gray-900">
          登录您的账户
        </h2>
        <p class="mt-2 text-center text-sm text-gray-600">
          或者
          <router-link to="/register" class="font-medium text-primary-600 hover:text-primary-500">
            创建新账户
          </router-link>
        </p>
      </div>
      
      <form class="mt-8 space-y-6" @submit.prevent="handleLogin">
        <div class="rounded-md shadow-sm -space-y-px">
          <div>
            <label for="username" class="sr-only">用户名</label>
            <input
              id="username"
              v-model="form.username"
              name="username"
              type="text"
              required
              class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-primary-500 focus:border-primary-500 focus:z-10 sm:text-sm"
              placeholder="用户名"
            />
          </div>
          <div>
            <label for="password" class="sr-only">密码</label>
            <input
              id="password"
              v-model="form.password"
              name="password"
              type="password"
              required
              class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md focus:outline-none focus:ring-primary-500 focus:border-primary-500 focus:z-10 sm:text-sm"
              placeholder="密码"
            />
          </div>
        </div>

        <div class="flex items-center justify-between">
          <div class="flex items-center">
            <input
              id="remember-me"
              v-model="form.rememberMe"
              name="remember-me"
              type="checkbox"
              class="h-4 w-4 text-primary-600 focus:ring-primary-500 border-gray-300 rounded"
            />
            <label for="remember-me" class="ml-2 block text-sm text-gray-900">
              记住我
            </label>
          </div>

          <div class="text-sm">
            <a href="#" class="font-medium text-primary-600 hover:text-primary-500">
              忘记密码？
            </a>
          </div>
        </div>

        <div>
          <button
            type="submit"
            :disabled="isLoading"
            class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-primary-600 hover:bg-primary-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-500 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <span v-if="isLoading" class="absolute left-0 inset-y-0 flex items-center pl-3">
              <svg class="animate-spin h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
              </svg>
            </span>
            {{ isLoading ? '登录中...' : '登录' }}
          </button>
        </div>

        <!-- 错误提示 -->
        <div v-if="error" class="rounded-md bg-red-50 p-4">
          <div class="flex">
            <div class="flex-shrink-0">
              <ExclamationTriangleIcon class="h-5 w-5 text-red-400" />
            </div>
            <div class="ml-3">
              <h3 class="text-sm font-medium text-red-800">
                登录失败
              </h3>
              <div class="mt-2 text-sm text-red-700">
                {{ error }}
              </div>
            </div>
          </div>
        </div>

        <!-- 微信登录 -->
        <div class="mt-6">
          <div class="relative">
            <div class="absolute inset-0 flex items-center">
              <div class="w-full border-t border-gray-300" />
            </div>
            <div class="relative flex justify-center text-sm">
              <span class="px-2 bg-gray-50 text-gray-500">或者使用</span>
            </div>
          </div>

          <div class="mt-6">
            <button
              type="button"
              @click="handleWechatLogin"
              class="w-full inline-flex justify-center py-2 px-4 border border-gray-300 rounded-md shadow-sm bg-white text-sm font-medium text-gray-500 hover:bg-gray-50"
            >
              <svg class="w-5 h-5 text-green-500" fill="currentColor" viewBox="0 0 24 24">
                <path d="M8.691 2.188C3.891 2.188 0 5.476 0 9.53c0 2.212 1.17 4.203 3.002 5.55a.59.59 0 0 1 .213.665l-.39 1.298c-.115.379.213.747.602.602l1.894-.793a.59.59 0 0 1 .602.088c1.285.793 2.82 1.212 4.768 1.212 4.8 0 8.691-3.288 8.691-7.342 0-4.054-3.891-7.342-8.691-7.342zm-2.46 9.746a.918.918 0 0 1-.918-.918V9.53a.918.918 0 0 1 1.836 0v1.486c0 .506-.41.918-.918.918zm4.919 0a.918.918 0 0 1-.918-.918V9.53a.918.918 0 0 1 1.836 0v1.486c0 .506-.41.918-.918.918z"/>
              </svg>
              <span class="ml-2">微信登录</span>
            </button>
          </div>
        </div>
      </form>
    </div>
  </div>
</template>

<script setup>
import { ref, reactive } from 'vue'
import { useRouter } from 'vue-router'
import { ExclamationTriangleIcon } from '@heroicons/vue/24/outline'
import { login, wechatLogin, isLoading } from '@/stores/auth'

const router = useRouter()
const error = ref('')

const form = reactive({
  username: '',
  password: '',
  rememberMe: false
})

const handleLogin = async () => {
  error.value = ''
  
  const result = await login({
    username: form.username,
    password: form.password
  })
  
  if (result.success) {
    router.push('/')
  } else {
    error.value = result.message
  }
}

const handleWechatLogin = async () => {
  // 这里应该集成微信登录SDK
  // 暂时显示提示信息
  alert('微信登录功能需要配置微信小程序参数')
}
</script>

// frontend/src/app/(c)/c/login/page.tsx
"use client";

import { Suspense, useActionState } from "react";
import { useSearchParams } from "next/navigation";
import Link from "next/link";
import { loginAction } from "@/lib/api-c/auth";
import type { ActionResult } from "@/lib/action-result";

function LoginForm() {
  const searchParams = useSearchParams();
  const redirect = searchParams.get("redirect") || "";

  const [state, formAction, isPending] = useActionState(
    loginAction,
    { success: false, error: "" } as ActionResult<null>
  );

  return (
    <section className="px-4 md:px-6 pt-8">
      <div className="max-w-md mx-auto">
        <form action={formAction} className="space-y-6">
          <div className="bg-white rounded-xl p-6 shadow-[0px_4px_20px_rgba(15,23,42,0.05)] border border-c-border-subtle">
            {state && !state.success && state.error && (
              <div className="mb-4 p-3 bg-red-50 border border-red-200 rounded-lg text-c-error text-sm">
                {state.error}
              </div>
            )}
            <input type="hidden" name="redirect" value={redirect} />
            <div className="mb-6">
              <label className="block text-xs font-bold text-c-text-secondary uppercase mb-2">用户名</label>
              <input
                type="text"
                name="username"
                placeholder="请输入用户名"
                required
                className="w-full bg-c-surface border border-c-border-subtle rounded-lg px-4 py-3 text-base text-c-text-primary placeholder:text-c-text-secondary focus:outline-none focus:ring-2 focus:ring-c-trust-blue/20 transition-all"
              />
            </div>
            <div className="mb-8">
              <label className="block text-xs font-bold text-c-text-secondary uppercase mb-2">密码</label>
              <input
                type="password"
                name="password"
                placeholder="请输入密码"
                required
                className="w-full bg-c-surface border border-c-border-subtle rounded-lg px-4 py-3 text-base text-c-text-primary placeholder:text-c-text-secondary focus:outline-none focus:ring-2 focus:ring-c-trust-blue/20 transition-all"
              />
            </div>
            <button
              type="submit"
              disabled={isPending}
              className="w-full bg-c-trust-blue text-white h-12 rounded-lg font-bold active:opacity-80 active:scale-95 transition-all shadow-sm disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {isPending ? "登录中..." : "登 录"}
            </button>
          </div>
        </form>
        <div className="text-center mt-8">
          <p className="text-sm text-c-text-secondary">还没有账号？</p>
          <Link href="/c/register" className="inline-flex items-center text-c-trust-blue font-bold gap-1 mt-2 hover:underline">
            前往注册
          </Link>
        </div>
      </div>
    </section>
  );
}

export default function CLoginPage() {
  return (
    <Suspense>
      <LoginForm />
    </Suspense>
  );
}
